### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by gnomelibre**
My first traduction and pull request :)

### CODE REVIEW

**Comment by murraycu** [comment]
If you could correct the commit, please, then I could apply it.

**Comment by gnomelibre** [comment]
hello :)

Is it ok, now?

**Comment by murraycu** [comment]
Thanks you. Could you please rebase them into one commit?

**Comment by gnomelibre** [comment]
It was laborious, but I think it's ok. Finally.

**Comment by murraycu** [comment]
Many thanks.

**Pull request merged**
