### PR TITLE
Use HeaderBar

### PR DESCRIPTION
**Pull request by juanrgar**

### CODE REVIEW

**Comment by murraycu** [comment]
I have taken those changes, but I had to rebase and also edit your commit, and ended up doing a git push -f. I suggest that you delete your fork and recreate it next time, or do some awkward rebasing.

By the way, is there any GNOME design guideline that says we should have those buttons on the left rather than on the right?
Thanks.

**Comment by juanrgar** [comment]
Sorry for not answering. Ok, I'll refork.

Mmm not sure about any guidelines, but for sure it is the trend I think.

**Comment by brunelli** [comment]
Somethings about this HeaderBar aren't right.
1. The title isn't centered, it makes the HeaderBar look unbalanced.
2. There are two buttons (`Rename Files` and `Stop`), and when one of them is active, the other one is inactive. I thing they could be merged in only one button.
3. The `Stop` button should be red, to indicate a "dangerous" action (clicking it will result in only part of the files being renamed).

**Comment by murraycu** [comment]
Thanks for the feedback.
1. Isn't that a general issue with all such GNOME applications?
2. In general, GNOME (or its HIG?) has discouraged changing button titles, I think.
3. This would be particularly odd in a GNOME app, I think. And though I see the danger of using the stop button, I don't think using red would be much of a solution to that problem. After all, you'd be pressing it in a hurry anyway. Making it more prominent could almost make it more likely to be clicked.

Isn't there a GNOME design mailing list that you could ask about these things? It's a simple app so maybe this would be a useful exercise.

**Comment by brunelli** [comment]
1. No? Or at least most of them seem very simetric/balanced. Maybe the issue is more highlighted here because of the default width being smaller when compared to other apps that makes use of a HeaderBar.
2. Okay, I didn't know that. So maybe you could move the `Stop` button and the progress bar into a modal dialog([like this one](https://github.com/gnome-design-team/gnome-mockups/blob/master/nautilus/nautilus-next/new-folder.png), but with the progress bar occupying the place of the textbox and just a `Stop` button on the HeaderBar)? I think this is a good solution because it makes the app "unusable" while running a task, and also avoids the `Close` button being hit while an operation is being performed.
3. I see your point. I've seen the red button used just in actions to remove/delete something... I don't know what the HIG says about this. :/ 

I don't think so, but the [gnome-mockups](https://github.com/gnome-design-team/gnome-mockups/) repo is a good place to see the HIGs in action.

**Pull request merged**
